index.ts
lib/generateMarkdown.ts
lib/getAllPRs.ts
lib/getMergedPRs.ts
package.json

- Review table added under Contributor Overview
<details>
<summary>Example</summary>
| Contributor | Reviews Received | Reviews Requested | Reviews Given | Changes Requested | PRs Opened | PRs Closed |
|-------------|------------------|-------------------|---------------|-------------------|------------|------------|
| [seveibar](https://github.com/seveibar) | 1 | 13 | 1 | 0 | 42 | 42 |
| [imrishabh18](https://github.com/imrishabh18) | 15 | 6 | 0 | 1 | 21 | 21 |
| [ShiboSoftwareDev](https://github.com/ShiboSoftwareDev) | 8 | 2 | 0 | 0 | 6 | 6 |
| [mrudulpatil18](https://github.com/mrudulpatil18) | 5 | 0 | 0 | 1 | 3 | 3 |
| [Abse2001](https://github.com/Abse2001) | 5 | 2 | 0 | 0 | 4 | 4 |
| [anas-sarkez](https://github.com/anas-sarkez) | 27 | 11 | 1 | 3 | 14 | 14 |
| …

feat: review table

---

lib/generateMarkdown.ts

Fix review table

---

lib/generateMarkdown.ts

Reverts tscircuit/contribution-tracker#11

Revert "Fix review table"

---

lib/generateMarkdown.ts

Fix: review table

---

index.ts
lib/generateMarkdown.ts
lib/getAllPRs.ts
lib/getIssuesCreated.ts

Fixes #16 
Fixes #19 
/claim #16
Screenshots: 
Before:
After:

feat: added bountied issue amount as a star factor

---

README.md
index.ts
lib/analyzePRWithClaude.ts
lib/cache.ts
lib/generateMarkdown.ts
lib/getAllPRs.ts
lib/getMergedPRs.ts
lib/getRepos.ts
lib/sdks.ts
lib/types.ts
tsconfig.json

- **break up files, fix all type issues**
- **Refactor types, add support for json generation, fix claude caching, fix column titles**
fixes #18

Refactor types, add support for json generation, fix claude caching, fix column titles

---

index.ts
lib/generateMarkdown.ts
lib/getAllPRs.ts
lib/types.ts

/closes #23
max 20 points across approvals and rejections

count approvals and rejections as tiny contribution points

---

.gitignore
index.ts
lib/analyzePRWithClaude.ts
lib/cachedAnthropic.ts
lib/sdks.ts

Fixes #29
Fixes #25
https://github.com/user-attachments/assets/f2c2eeb5-50ba-4bda-a591-b2be6263799f
https://github.com/user-attachments/assets/0dac1c32-42eb-432f-bb02-a8a18952a42f

add cache to claude-anthropic

---

README.md

docs: Approvals -> Approval sents

---

lib/generateMarkdown.ts
lib/getAllPRs.ts
lib/types.ts
tests/test-pr-scoring.test.ts

feat: Reviews should only count once per PR

---

frontend/src/hooks/useContributorsData.ts
frontend/src/types/contributor.ts

fix: use score to sort contributors instead of stars

---

frontend/src/components/ContributorGraph.tsx

feat: add faded lines for stars in contributor graph

---

frontend/src/components/ContributorOverview.tsx

add github link for top contributors

add github link for top contributors

---

frontend/src/components/ContributorGraph.tsx

style: add small shadow to and gap under graph

---

frontend/src/App.tsx

tweak: navbar ui on desktop 

---

.github/workflows/bun-formatcheck.yml
.github/workflows/bun-test.yml
.github/workflows/bun-typecheck.yml
biome.json

Introduce workflows to automate format checking, testing, and type checking on push and pull request events.
Closes #70

Add GitHub workflows for format check, testing, and type checking

---

lib/getAllPRs.ts
lib/getMergedPRs.ts

patch: require approval for points

---

.github/workflows/update-sponsorships.yml
scripts/generate-sponsorship-csv.ts
sponsorships/2025-02.csv

feat: automate sponsorship payments with daily CSV generation

---

bun.lock
frontend/src/components/ContributorCard.tsx
frontend/src/components/ContributorOverview.tsx
frontend/src/constants/tooltips.ts
package.json

feat: add tooltips to contribution icons and stats (#69)

---

frontend/index.html
frontend/src/App.tsx
frontend/src/hooks/useContributorsData.ts

feat: add loading state to contributors data fetching

---

.github/workflows/sync-discord-roles.yml

ci(discord-sync): updated roles update schedule to Wednesday

---

frontend/src/components/ContributorOverview.tsx

Improve the layout and spacing in the ContributorOverview component to enhance responsiveness and alignment across different screen sizes. Changes include adjusting flex properties, widths, and margins to ensure a more consistent and visually appealing display.
(outdated preview)

style(ContributorOverview): adjust layout and spacing for better responsiveness

---

frontend/src/components/ContributorOverview.tsx

style(ContributorOverview): update ring and background colors for 2nd place

---

frontend/src/hooks/useContributorsData.ts

fix #114 
fix #110
The changes allow the hook to process PR rows in tables with and without contributor information. This ensures compatibility with different markdown formats and improves the robustness of the data extraction logic.

refactor(useContributorsData): handle both PR formats with and without contributor

---

frontend/src/components/ContributorOverview.tsx
frontend/src/constants/contributors.ts
lib/data-retrieval/getMergedPRs.ts
scripts/generate-sponsorship-csv.ts

add andrii-balitskyi to staff list

---

.github/workflows/update-contribution-overview.yml

chore: add pr-analysis to commit

---

index.ts

patch: not able to fetch pr impact gracefully

---

frontend/src/components/PrsTable.tsx
frontend/src/constants/metrics.ts

add colors to text in impact column

---

index.ts
lib/ai/analyzePRWithClaude.ts

Refactor impact assignment logic in PR analysis

---

index.ts

Sort contributor data alphabetically before writing to JSON file in contribution overviews

---

frontend/src/hooks/useContributorsData.ts
index.ts
lib/ai/date-utils.ts
lib/data-retrieval/getAllDiscussionComments.ts
lib/data-retrieval/getAllPRs.ts
lib/data-retrieval/getMergedPRs.ts
scripts/generate-sponsorship-csv.ts
scripts/generate-this-month-overview.ts
tests/test-date-calc.test.ts

- Updated date normalization in getLastWednesday to use UTC.
- Adjusted date calculations in useContributorsData to utilize UTC methods.
- Modified date comparisons in getAllDiscussionComments, getAllPRs, and getMergedPRs to use getTime for consistency.
- Changed date handling in generate-sponsorship-csv and generate-this-month-overview to ensure UTC compliance.
- Updated tests to verify UTC normalization for date calculations.

refactor(date): use UTC for date handling across modules

---

.github/workflows/update-contribution-overview.yml
index.ts

feat(logging): add console logs for processed issues and discussions in overview generation

---

lib/ai-stuff/analyze-pr.ts
lib/ai-stuff/prompts.ts

Refactor PR analysis structure and enhance discussion comment classification criteria for improved clarity and strictness.

---

.github/workflows/discord-notifications.yml
bun.lock
lib/ai-stuff/analyze-pr.ts
lib/ai/analyzePRWithClaude.ts
lib/data-processing/filter-diff.ts
lib/data-retrieval/getAllPRs.ts
lib/data-retrieval/getMergedPRs.ts
lib/data-retrieval/getOpenedPRs.ts
lib/notifications/notify-pr-change.ts
lib/types.ts
package.json
scripts/issue-notifications.ts
scripts/pr-notifications.ts

feat!: integrate notifications system

---

index.ts

…
fix #146
asked by shibo or sev idk forogt

add some PR analysis logging

---

index.ts
lib/data-processing/generateMarkdown.ts

Now only count repos in a week wenesday to wendesday + show star rating on readme

---

frontend/src/types/contributor.ts
index.ts
lib/data-retrieval/getAllPRs.ts
lib/scoring/getContributorScore.ts
lib/types.ts
tests/test-pr-scoring.test.ts

fix #195
Co-authored-by: ShiboSoftwareDev <shibosoftwaredev@gmail.com>

Codeowners review cap at 10 instead of usual 5 

---

index.ts
lib/data-processing/generateMarkdown.ts
tests/__snapshots__/test-generate-markdown.test.ts.snap
tests/test-generate-markdown.test.ts

refactor(fetchCodeowners): show every repo code owners gracefully, fix not showing before

---

lib/data-processing/generateMarkdown.ts
tests/__snapshots__/test-generate-markdown.test.ts.snap
tests/test-generate-markdown.test.ts

patch(followup-codeowners-final): skip empty owners in markdown for repos

---

frontend/src/App.tsx
frontend/src/components/MaintainersList.tsx

feat: maintainers list

---

.github/workflows/sync-discord-roles.yml
scripts/sync-discord-roles.ts

feat: crown notifications
